# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on:
  push:
    branches:
      - main
jobs:
  fly-config-validate:
    name: Validate Fly.io config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate config
        run: flyctl config validate  --app ${{ secrets.APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  dockerfile-lint:
    name: Run Hadolint on Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Docker files with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: Dockerfile
          format: tty
          strict-labels: true
          failure-threshold: warning
  deploy:
    name: Deploy app on Fly.io
    runs-on: ubuntu-latest
    needs:
      - fly-config-validate
      - dockerfile-lint
    steps:
      - uses: actions/checkout@v4
      - name: Write rclone config secret to file
        env:
          RCLONE_CONFIG: ${{secrets.RCLONE_CONFIG}}
        shell: bash
        run: |
          echo "$RCLONE_CONFIG" > rclone.config
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only --app ${{ secrets.APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
