# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on:
  push:
    branches:
      - main
jobs:
  fly-config-validate:
    name: Validate Fly.io config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate config
        run: flyctl config validate  --app ${{ secrets.APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  dockerfile-lint:
    name: Run Hadolint on Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Docker files with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: Dockerfile
          format: tty
          strict-labels: true
          failure-threshold: warning
  deploy:
    name: Deploy app on Fly.io
    runs-on: ubuntu-latest
    needs:
      - fly-config-validate
      - dockerfile-lint
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: dopplerhq/secrets-fetch-action@v1.2.0
        id: doppler_b2
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN_B2 }}
      - run: echo "${{ steps.doppler_b2.outputs.CONFIG }}" > services/b2.toml
      - uses: dopplerhq/secrets-fetch-action@v1.2.0
        id: doppler_ftp
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN_FTP }}
      - run: echo "${{ steps.doppler_ftp.outputs.CONFIG }}" > services/ftp.toml
      - name: Deploy
        run: flyctl deploy --remote-only --app ${{ secrets.APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
